version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: flight_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --port=5001

  frontend:
    build:
      context: ./frontend
    container_name: flight_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html